Repository nanome-ai/nanome-lib, pull requests merged in 2019-06, with the labels that each got.

#38 Different serial fix
  nanome/_internal/_structure/_atom.py
  nanome/_internal/_structure/_serialization/_atom_serializer.py
  nanome/_internal/_structure/_serialization/_atom_serializer_id.py
  testing/atom_tests.py
  testing/mmcif_tests.py
  testing/sdf_tests.py
Labels: bugfix

#33 config
  nanome/_internal/_plugin.py
  nanome/api/plugin.py
  nanome/util/config.py
  setup.py
  setup_config.py
  test_plugins/RemoveHydrogens.py
  test_plugins/UIPlugin.py
Labels: enhancement

#39 Data class optimization
  nanome/_internal/_network/_data.py
Labels: optimization

#37 Fixed reparent problem
  nanome/api/structure/chain.py
  nanome/api/structure/complex.py
  nanome/api/structure/molecule.py
  nanome/api/structure/residue.py
  nanome/util/vector3.py
  test_plugins/SandBox.py
Labels: bugfix
