Repository nanome-ai/nanome-lib, pull requests merged in 2019-07, with the labels that each got.

#48 Documentation v0.02
  doc/docsAssets/2Dmode_plugins.png
  doc/docsAssets/RunningNTS.png
  doc/docsAssets/browse_path.png
  doc/docsAssets/edit_path.png
  doc/docsAssets/find_env.png
  doc/docsAssets/running_plugin.png
  doc/docsAssets/search_env.png
  doc/docsAssets/webloader_browserprompt.png
  doc/docsAssets/webloader_uploaded.png
  doc/source/index.rst
  doc/source/installation.rst
Labels: meta

#50 Add an argument to rename a plugin temporarily
  nanome/_internal/_plugin.py
Labels: enhancement

#47 Prevent cast exception deserializers
  nanome/_internal/_structure/_serialization/_atom_serializer.py
  nanome/_internal/_structure/_serialization/_bond_serializer.py
  nanome/_internal/_structure/_serialization/_residue_serializer.py
  nanome/util/enums.py
Labels: bugfix

#52 Add atom scale to protocol
  nanome/_internal/_structure/_atom.py
  nanome/_internal/_structure/_serialization/_atom_serializer.py
  nanome/api/structure/atom.py
Labels: enhancement, protocol

#41 [NP-4395] IncrementedVersionNumbers
  nanome/_internal/_network/_commands/_serialization/_button_callback.py
  nanome/_internal/_network/_commands/_serialization/_image_callback.py
  nanome/_internal/_network/_commands/_serialization/_slider_callback.py
  nanome/_internal/_network/_commands/_serialization/_text_input_callback.py
  nanome/_internal/_ui/_serialization/_button_serializer.py
  nanome/_internal/_ui/_serialization/_image_serializer.py
  nanome/_internal/_ui/_serialization/_label_serializer.py
  nanome/_internal/_ui/_serialization/_layout_node_serializer.py
  nanome/_internal/_ui/_serialization/_loading_bar_serializer.py
  nanome/_internal/_ui/_serialization/_mesh_serializer.py
  nanome/_internal/_ui/_serialization/_slider_serializer.py
  nanome/_internal/_ui/_serialization/_text_input_serializer.py
  nanome/_internal/_ui/_serialization/_ui_list_serializer.py
  test_plugins/UIPlugin.py
Labels: protocol

#42 Add a process API to execute and interact with external processes
  nanome/_internal/_network/_process_network.py
  nanome/_internal/_network/_session.py
  nanome/_internal/_plugin.py
  nanome/_internal/_plugin_instance.py
  nanome/_internal/_process/__init__.py
  nanome/_internal/_process/_process_entry.py
  nanome/_internal/_process/_process_manager.py
  nanome/_internal/_process/_process_manager_instance.py
  nanome/api/plugin.py
  nanome/util/__init__.py
  nanome/util/process.py
Labels: enhancement

#45 Wrap bond and dssp
  nanome/_internal/_process/__init__.py
  nanome/_internal/_process/_bonding.py
  nanome/_internal/_process/_dssp.py
  nanome/_internal/_process/_external/_dssp/dssp-3.0.0-win32.exe
  nanome/_internal/_process/_external/_dssp/dssp-linux
  nanome/_internal/_process/_process_manager.py
  nanome/_internal/_structure/_atom.py
  nanome/_internal/_structure/_residue.py
  nanome/api/plugin_instance.py
  setup.py
Labels: enhancement

#54 Fix an exception with stream interrupt and add a stream test plugin
  nanome/api/streams/stream.py
  test_plugins/StreamTest.py
Labels: bugfix
