Repository nanome-ai/nanome-lib, pull requests merged in 2021-05, with the labels that each got.

#165 Multi tags and integrations + permissions
  nanome/_internal/_network/_commands/_callbacks/_commands_enums.py
  nanome/_internal/_network/_commands/_serialization/_integration.py
  nanome/_internal/_plugin.py
  nanome/_internal/_plugin_instance.py
  nanome/api/files.py
  nanome/api/integration/integration.py
  nanome/api/plugin.py
  nanome/util/enums.py
  test_plugins/FileExplorer.py
  test_plugins/SandBox.py
  test_plugins/UIPlugin.py
Labels: enhancement, invalid, protocol

#192 Fix permissions and tags
  nanome/_internal/_plugin_instance.py
  nanome/api/files.py
  nanome/api/plugin.py
  test_plugins/FileExplorer.py
Labels: bugfix

#195 Add an option to disable writing HET atoms in PDB files
  nanome/_internal/_structure/_io/_pdb/save.py
  nanome/util/complex_save_options.py
Labels: enhancement

#183 Fix connection restart request
  nanome/_internal/_network/_net_instance.py
  nanome/_internal/_plugin.py
Labels: bugfix

#196 Fix timeout when nts forces plugin disconnection
  nanome/_internal/_network/_serialization/_serializer.py
  nanome/_internal/_plugin.py
Labels: bugfix
